[package]
name = "tools"
version = "0.1.0"
authors = ["Jorge Aparicio <jorge@japaric.io>"]
edition = "2018"

[dependencies]
clap = "2.31.1"
failure = "0.1.1"
jnet = { path = ".." }
url = "1.7.0"
rand = "0.6.5"
libc = "0.2.49"
